# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Zybo7000.xdc

# Block Designs: bd/block_adc/block_adc.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_adc || ORIG_REF_NAME==block_adc} -quiet] -quiet

# IP: bd/block_adc/ip/block_adc_processing_system7_0_0/block_adc_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_adc_processing_system7_0_0 || ORIG_REF_NAME==block_adc_processing_system7_0_0} -quiet] -quiet

# IP: bd/block_adc/ip/block_adc_xadc_wiz_0_0/block_adc_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_adc_xadc_wiz_0_0 || ORIG_REF_NAME==block_adc_xadc_wiz_0_0} -quiet] -quiet

# IP: bd/block_adc/ip/block_adc_auto_pc_0/block_adc_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_adc_auto_pc_0 || ORIG_REF_NAME==block_adc_auto_pc_0} -quiet] -quiet

# IP: bd/block_adc/ip/block_adc_ps7_0_axi_periph_0/block_adc_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_adc_ps7_0_axi_periph_0 || ORIG_REF_NAME==block_adc_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/block_adc/ip/block_adc_rst_ps7_0_100M_0/block_adc_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_adc_rst_ps7_0_100M_0 || ORIG_REF_NAME==block_adc_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: bd/block_adc/block_adc_ooc.xdc
