webtalk_init -webtalk_dir /home/jonas/Documents/SDU/Master/Semester1/Project/software/git/gokart_inverter/inverterControl/inverterControl.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2019-03-04 07:00:52" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "rg4s4j4k3jk2jb0n90q4s6640s" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.3_2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.1 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-3317U CPU @ 1.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2394.756 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.245 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1551678261000" -context "sdk\\\\application/1551678261000"
webtalk_add_data -client sdk -key hwid -value "1551347137000" -context "sdk\\\\application/1551678261000"
webtalk_add_data -client sdk -key bspid -value "1551347184000" -context "sdk\\\\application/1551678261000"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1551678261000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1551678261000"
webtalk_add_data -client sdk -key apptemplate -value "zynq_fsbl" -context "sdk\\\\application/1551678261000"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1551678261000"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1551678261000"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1551678261000"
webtalk_add_data -client sdk -key projSize -value "596.23828125" -context "sdk\\\\application/1551678261000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1551679252271"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1551679252271"
webtalk_add_data -client sdk -key BootgenCount -value "1" -context "sdk\\\\bsp/1551679252271"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1551679252271"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1551679252271"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1551679252271"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1551679252271"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1551679252271"
webtalk_transmit -clientid 3948933039 -regid "" -xml /home/jonas/Documents/SDU/Master/Semester1/Project/software/git/gokart_inverter/inverterControl/inverterControl.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/jonas/Documents/SDU/Master/Semester1/Project/software/git/gokart_inverter/inverterControl/inverterControl.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/jonas/Documents/SDU/Master/Semester1/Project/software/git/gokart_inverter/inverterControl/inverterControl.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
